"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { audit } from "@/lib/audit";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { addMemberActivity, assertMemberAccess } from "@/lib/members";

const id = z.string().cuid();
const interventionTypes = ["TRAINER_CHECK_IN", "GOAL_REVIEW", "PROGRAM_REASSESSMENT", "PERSONAL_OUTREACH", "PT_CONSULTATION", "RENEWAL_DISCUSSION", "WELCOME_CHECK_IN", "PROGRESS_CELEBRATION", "MEMBER_COMPLAINT_FOLLOW_UP", "MANAGER_REVIEW", "SAFETY_ESCALATION", "RECOVERY_CHECK_IN", "OTHER"] as const;
const priorities = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "OPPORTUNITY"] as const;
const refresh = (memberId?: string, interventionId?: string) => { revalidatePath("/trainer"); revalidatePath("/attention"); if (memberId) { revalidatePath(`/members/${memberId}`); revalidatePath(`/members/${memberId}/intelligence`); } if (interventionId) revalidatePath(`/trainer/interventions/${interventionId}`); };

async function interventionAccess(interventionId: string, write = true) {
  const actor = await requireUser("members:write"); const item = await db.intervention.findFirstOrThrow({ where: { id: interventionId, gymId: actor.gymId } }); await assertMemberAccess(actor, item.memberId, write);
  if (actor.role === "TRAINER" && item.assignedToId !== actor.id) throw new Error("Only the assigned trainer can act on this intervention.");
  return { actor, item };
}

export async function createIntervention(formData: FormData) {
  const actor = await requireUser("members:write"); const data = z.object({ memberId: id, attentionItemId: z.string().cuid().optional().or(z.literal("")), type: z.enum(interventionTypes), title: z.string().trim().max(160).optional(), reason: z.string().trim().min(3).max(600), recommendedAction: z.string().trim().min(3).max(300), priority: z.enum(priorities).optional(), assignedToId: z.string().cuid().optional().or(z.literal("")), dueAt: z.string().min(10), notes: z.string().trim().max(1600).optional() }).parse(Object.fromEntries(formData));
  const member = await assertMemberAccess(actor, data.memberId, true); const attention = data.attentionItemId ? await db.attentionItem.findFirst({ where: { id: data.attentionItemId, gymId: actor.gymId, memberId: member.id } }) : null;
  const assigneeId = data.assignedToId || (actor.role === "TRAINER" ? actor.id : member.trainerId); if (actor.role === "TRAINER" && assigneeId !== actor.id) throw new Error("Trainers can only assign work to themselves.");
  const assignee = assigneeId ? await db.user.findFirst({ where: { id: assigneeId, gymId: actor.gymId, role: "TRAINER" } }) : null; const now = new Date(); const title = data.title || attention?.title || data.type.replaceAll("_", " ");
  const intervention = await db.intervention.create({ data: { gymId: actor.gymId, memberId: member.id, attentionItemId: attention?.id, type: data.type, title, reason: data.reason, recommendedAction: data.recommendedAction, priority: data.priority || attention?.priority || "MEDIUM", assignedToId: assignee?.id, assignedRole: assignee ? "TRAINER" : "UNASSIGNED", createdByUserId: actor.id, assignedAt: assignee ? now : null, status: assignee ? "ASSIGNED" : "OPEN", dueAt: new Date(data.dueAt), notes: data.notes || null } });
  if (assignee) await db.interventionAssignment.create({ data: { gymId: actor.gymId, interventionId: intervention.id, newAssigneeId: assignee.id, changedByUserId: actor.id, reason: "Initial assignment" } });
  if (attention) await db.attentionItem.update({ where: { id: attention.id }, data: { status: "IN_PROGRESS", assignedUserId: assignee?.id ?? attention.assignedUserId } });
  await addMemberActivity({ gymId: actor.gymId, memberId: member.id, actorId: actor.id, type: "INTERVENTION_CREATED", message: `${title} intervention created.` }); await audit({ gymId: actor.gymId, actorId: actor.id, action: "INTERVENTION_CREATED", entityType: "Intervention", entityId: intervention.id, after: { memberId: member.id, title, priority: intervention.priority, assignedToId: assignee?.id } }); refresh(member.id, intervention.id);
}

export async function startIntervention(formData: FormData) { const { actor, item } = await interventionAccess(id.parse(formData.get("interventionId"))); const now = new Date(); await db.intervention.update({ where: { id: item.id }, data: { status: "IN_PROGRESS", startedAt: item.startedAt ?? now } }); await addMemberActivity({ gymId: actor.gymId, memberId: item.memberId, actorId: actor.id, type: "INTERVENTION_STARTED", message: `${item.title} started.` }); await audit({ gymId: actor.gymId, actorId: actor.id, action: "INTERVENTION_STARTED", entityType: "Intervention", entityId: item.id }); refresh(item.memberId, item.id); }

export async function completeIntervention(formData: FormData) {
  const data = z.object({ interventionId: id, actionTaken: z.string().trim().min(3).max(1600), memberResponse: z.string().trim().max(1200).optional(), followUpAt: z.string().optional(), notes: z.string().trim().max(1600).optional(), resolutionSummary: z.string().trim().max(800).optional(), interactionType: z.enum(["IN_PERSON", "PHONE", "SIMULATED_MESSAGE", "PROGRESS_REVIEW", "PROGRAM_UPDATE", "PT_CONSULTATION", "GOAL_REVIEW", "GENERAL_CHECK_IN"]).optional() }).parse(Object.fromEntries(formData));
  const { actor, item } = await interventionAccess(data.interventionId); const followUp = data.followUpAt ? new Date(data.followUpAt) : null; const status = followUp ? "FOLLOW_UP_DUE" : "COMPLETED"; const now = new Date();
  await db.$transaction([db.intervention.update({ where: { id: item.id }, data: { status, actionTaken: data.actionTaken, memberResponse: data.memberResponse || null, followUpAt: followUp, notes: data.notes || item.notes, resolutionSummary: data.resolutionSummary || null, completedAt: now } }), db.trainerInteraction.create({ data: { gymId: actor.gymId, memberId: item.memberId, trainerId: actor.id, interventionId: item.id, type: data.interactionType || "GENERAL_CHECK_IN", notes: data.actionTaken, occurredAt: now } }), ...(item.attentionItemId ? [db.attentionItem.update({ where: { id: item.attentionItemId }, data: { status: "IN_PROGRESS", resolution: `Intervention completed${followUp ? "; follow-up due." : "."}` } })] : [])]);
  await addMemberActivity({ gymId: actor.gymId, memberId: item.memberId, actorId: actor.id, type: "INTERVENTION_COMPLETED", message: `${item.title} completed.${followUp ? " Follow-up scheduled." : ""}` }); await audit({ gymId: actor.gymId, actorId: actor.id, action: "INTERVENTION_COMPLETED", entityType: "Intervention", entityId: item.id, after: { followUpAt: followUp, status } }); refresh(item.memberId, item.id);
}

export async function assignIntervention(formData: FormData) { const actor = await requireUser("members:manage"); const interventionId = id.parse(formData.get("interventionId")); const assignedToId = id.parse(formData.get("assignedToId")); const reason = z.string().trim().max(500).optional().parse(formData.get("reason")); const [item, trainer] = await Promise.all([db.intervention.findFirstOrThrow({ where: { id: interventionId, gymId: actor.gymId } }), db.user.findFirstOrThrow({ where: { id: assignedToId, gymId: actor.gymId, role: "TRAINER" } })]); const now = new Date(); await db.$transaction([db.intervention.update({ where: { id: item.id }, data: { assignedToId: trainer.id, assignedRole: "TRAINER", assignedAt: now, status: item.status === "OPEN" ? "ASSIGNED" : item.status } }), db.interventionAssignment.create({ data: { gymId: actor.gymId, interventionId: item.id, previousAssigneeId: item.assignedToId, newAssigneeId: trainer.id, changedByUserId: actor.id, reason } })]); await addMemberActivity({ gymId: actor.gymId, memberId: item.memberId, actorId: actor.id, type: "INTERVENTION_ASSIGNED", message: `${item.title} assigned to ${trainer.name}.` }); await audit({ gymId: actor.gymId, actorId: actor.id, action: "INTERVENTION_ASSIGNED", entityType: "Intervention", entityId: item.id, before: { assignedToId: item.assignedToId }, after: { assignedToId: trainer.id } }); refresh(item.memberId, item.id); }

export async function manageIntervention(formData: FormData) { const actor = await requireUser("members:manage"); const data = z.object({ interventionId: id, dueAt: z.string().optional(), priority: z.enum(priorities).optional(), status: z.enum(["OPEN", "ASSIGNED", "IN_PROGRESS", "COMPLETED", "FOLLOW_UP_DUE", "CLOSED", "CANCELLED"]).optional(), notes: z.string().trim().max(1600).optional() }).parse(Object.fromEntries(formData)); const item = await db.intervention.findFirstOrThrow({ where: { id: data.interventionId, gymId: actor.gymId } }); await db.intervention.update({ where: { id: item.id }, data: { dueAt: data.dueAt ? new Date(data.dueAt) : undefined, priority: data.priority, status: data.status, notes: data.notes || undefined } }); await audit({ gymId: actor.gymId, actorId: actor.id, action: "INTERVENTION_MANAGED", entityType: "Intervention", entityId: item.id }); refresh(item.memberId, item.id); }
