"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { audit } from "@/lib/audit";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { addMemberActivity, assertMemberAccess } from "@/lib/members";
import { refreshJourneyStatus } from "@/lib/journey";

const id = z.string().cuid();
const refresh = (memberId: string) => { revalidatePath("/journeys"); revalidatePath("/trainer"); revalidatePath(`/members/${memberId}`); revalidatePath(`/members/${memberId}/journey`); };
export async function completeJourneyTask(formData: FormData) { const data = z.object({ taskId: id, notes: z.string().trim().max(1600).optional() }).parse(Object.fromEntries(formData)); const actor = await requireUser("members:write"); const task = await db.journeyTask.findFirstOrThrow({ where: { id: data.taskId, gymId: actor.gymId }, include: { journey: true } }); await assertMemberAccess(actor, task.memberId, true); if (actor.role === "TRAINER" && task.assignedUserId && task.assignedUserId !== actor.id) throw new Error("Only the assigned trainer can complete this journey task."); await db.journeyTask.update({ where: { id: task.id }, data: { status: "COMPLETED", completedAt: new Date(), notes: data.notes || null } }); if (task.taskType === "CONFIDENCE_CHECK" && /confused|support/i.test(data.notes || "")) { const key = `${actor.gymId}:${task.memberId}:journey-confidence`; const attention = await db.attentionItem.upsert({ where: { deduplicationKey: key }, create: { gymId: actor.gymId, memberId: task.memberId, ruleId: "journey-confidence", title: "New member needs exercise support", reason: "The guided-experience confidence check recorded confusion or a need for support.", priority: "HIGH", recommendedAction: "Trainer follow-up during the next workout.", assignedRole: "TRAINER", assignedUserId: task.assignedUserId, dueAt: new Date(Date.now() + 2 * 86_400_000), deduplicationKey: key }, update: { status: "IN_PROGRESS", reason: "The guided-experience confidence check recorded confusion or a need for support." } }); await db.intervention.upsert({ where: { deduplicationKey: `${key}:intervention` }, create: { gymId: actor.gymId, memberId: task.memberId, attentionItemId: attention.id, type: "WELCOME_CHECK_IN", title: "New-member confidence follow-up", reason: attention.reason, recommendedAction: attention.recommendedAction, priority: "HIGH", assignedRole: "TRAINER", assignedToId: task.assignedUserId, dueAt: attention.dueAt, status: task.assignedUserId ? "ASSIGNED" : "OPEN", deduplicationKey: `${key}:intervention` }, update: {} }); }
  await refreshJourneyStatus(task.journeyId); await addMemberActivity({ gymId: actor.gymId, memberId: task.memberId, actorId: actor.id, type: "JOURNEY_TASK_COMPLETED", message: `${task.title} completed.` }); await audit({ gymId: actor.gymId, actorId: actor.id, action: "JOURNEY_TASK_COMPLETED", entityType: "JourneyTask", entityId: task.id }); refresh(task.memberId); }
export async function setJourneyStatus(formData: FormData) { const data = z.object({ journeyId: id, status: z.enum(["ACTIVE", "PAUSED", "CANCELLED"]) }).parse(Object.fromEntries(formData)); const actor = await requireUser("members:manage"); const journey = await db.memberJourney.findFirstOrThrow({ where: { id: data.journeyId, gymId: actor.gymId } }); await db.memberJourney.update({ where: { id: journey.id }, data: { status: data.status } }); await audit({ gymId: actor.gymId, actorId: actor.id, action: `JOURNEY_${data.status}`, entityType: "MemberJourney", entityId: journey.id }); refresh(journey.memberId); }
