"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { audit } from "@/lib/audit";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { addMemberActivity, assertMemberAccess } from "@/lib/members";

const memberId = z.string().cuid(); const value = z.coerce.number().finite(); const date = z.coerce.date();
const refresh = (id: string) => { revalidatePath(`/members/${id}/progress`); revalidatePath(`/members/${id}`); revalidatePath("/"); };
export async function addGoal(formData: FormData) { const user = await requireUser("members:write"); const id = memberId.parse(formData.get("memberId")); await assertMemberAccess(user, id, true); const data = z.object({ type:z.string().min(2), title:z.string().min(2), startingValue:value.optional(), targetValue:value.optional(), unit:z.string().optional(), targetDate:z.coerce.date().optional(), isPrimary:z.string().optional() }).parse(Object.fromEntries(formData)); if (data.isPrimary) await db.goal.updateMany({ where:{memberId:id,status:"ACTIVE"},data:{isPrimary:false} }); const goal = await db.goal.create({ data:{gymId:user.gymId,memberId:id,type:data.type,title:data.title,startingValue:data.startingValue,targetValue:data.targetValue,unit:data.unit,startDate:new Date(),targetDate:data.targetDate,isPrimary:Boolean(data.isPrimary)} }); await addMemberActivity({gymId:user.gymId,memberId:id,actorId:user.id,type:"GOAL_CREATED",message:`Goal created: ${goal.title}.`}); await audit({gymId:user.gymId,actorId:user.id,action:"GOAL_CREATED",entityType:"Goal",entityId:goal.id}); refresh(id); }
export async function addMetric(formData: FormData) { const user=await requireUser("members:write"); const id=memberId.parse(formData.get("memberId")); await assertMemberAccess(user,id,true); const data=z.object({type:z.string().min(2),value,valueUnit:z.string().min(1),recordedAt:date,source:z.string().min(2),notes:z.string().max(600).optional()}).parse(Object.fromEntries(formData)); const metric=await db.progressMetric.create({data:{gymId:user.gymId,memberId:id,type:data.type,value:data.value,unit:data.valueUnit,recordedAt:data.recordedAt,source:data.source,notes:data.notes}}); await addMemberActivity({gymId:user.gymId,memberId:id,actorId:user.id,type:"METRIC_RECORDED",message:`${metric.type} recorded: ${metric.value} ${metric.unit}.`}); await audit({gymId:user.gymId,actorId:user.id,action:"METRIC_RECORDED",entityType:"ProgressMetric",entityId:metric.id}); refresh(id); }
export async function addAssessment(formData: FormData) { const user=await requireUser("members:write"); const id=memberId.parse(formData.get("memberId")); await assertMemberAccess(user,id,true); const data=z.object({assessedAt:date,weight:z.coerce.number().finite().optional(),bodyFat:z.coerce.number().finite().optional(),strength:z.string().max(600).optional(),endurance:z.string().max(600).optional(),mobility:z.string().max(600).optional(),notes:z.string().max(1200).optional()}).parse(Object.fromEntries(formData)); const assessment=await db.assessment.create({data:{gymId:user.gymId,memberId:id,trainerId:user.role==="TRAINER"?user.id:undefined,...data}}); await addMemberActivity({gymId:user.gymId,memberId:id,actorId:user.id,type:"ASSESSMENT_RECORDED",message:"Assessment recorded."}); await audit({gymId:user.gymId,actorId:user.id,action:"ASSESSMENT_RECORDED",entityType:"Assessment",entityId:assessment.id}); refresh(id); }
export async function addReview(formData: FormData) { const user=await requireUser("members:write"); const id=memberId.parse(formData.get("memberId")); await assertMemberAccess(user,id,true); const data=z.object({attendance:z.string().max(300).optional(),adherence:z.string().max(300).optional(),improvements:z.string().max(800).optional(),problems:z.string().max(800).optional(),planChanges:z.string().max(800).optional(),nextReviewDate:date.optional(),notes:z.string().max(1200).optional()}).parse(Object.fromEntries(formData)); const review=await db.progressReview.create({data:{gymId:user.gymId,memberId:id,trainerId:user.role==="TRAINER"?user.id:undefined,reviewedAt:new Date(),...data}}); await addMemberActivity({gymId:user.gymId,memberId:id,actorId:user.id,type:"PROGRESS_REVIEW",message:"Progress review completed."}); await audit({gymId:user.gymId,actorId:user.id,action:"PROGRESS_REVIEW",entityType:"ProgressReview",entityId:review.id}); refresh(id); }

export async function addMilestone(formData: FormData) { const user=await requireUser("members:write"); const id=memberId.parse(formData.get("memberId")); await assertMemberAccess(user,id,true); const data=z.object({type:z.string().min(2),title:z.string().min(2).max(120),description:z.string().max(500).optional()}).parse(Object.fromEntries(formData)); const milestone=await db.milestone.create({data:{gymId:user.gymId,memberId:id,type:data.type,title:data.title,description:data.description,achievedAt:new Date(),isAutomatic:false}}); await addMemberActivity({gymId:user.gymId,memberId:id,actorId:user.id,type:"MILESTONE_ADDED",message:"Milestone added: "+milestone.title+"."}); await audit({gymId:user.gymId,actorId:user.id,action:"MILESTONE_ADDED",entityType:"Milestone",entityId:milestone.id}); refresh(id); }
