"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { audit } from "@/lib/audit";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { canUseScenario, scenarioFor } from "@/lib/training";

function refresh() { revalidatePath("/training"); revalidatePath("/", "layout"); }
async function ensureTrainingRecords(gymId: string) { const trainer = await db.user.findFirst({ where: { gymId, role: "TRAINER" } }); const aman = await db.member.upsert({ where: { gymId_email: { gymId, email: "training.aman@demo.gym" } }, create: { gymId, fullName: "Aman — Declining Training Member", email: "training.aman@demo.gym", phone: "+91 90000 99999", membershipStatus: "ACTIVE", memberState: "DECLINING", attentionLevel: "HIGH", joinDate: new Date(Date.now() - 120 * 86400000), membershipEnd: new Date(Date.now() + 60 * 86400000), assignedTrainer: trainer?.name, trainerId: trainer?.id, goal: "Return to consistent training", lastVisit: new Date(Date.now() - 12 * 86400000) }, update: { fullName: "Aman — Declining Training Member", memberState: "DECLINING", attentionLevel: "HIGH", assignedTrainer: trainer?.name, trainerId: trainer?.id, lastVisit: new Date(Date.now() - 12 * 86400000) } }); if (!await db.membership.findFirst({ where: { gymId, memberId: aman.id } })) await db.membership.create({ data: { gymId, memberId: aman.id, planName: "Training membership", amount: 0, status: "ACTIVE", startDate: new Date(Date.now() - 120 * 86400000), endDate: new Date(Date.now() + 60 * 86400000) } }); await db.attentionItem.upsert({ where: { deduplicationKey: `${gymId}:training:aman:attention` }, create: { gymId, memberId: aman.id, ruleId: "training-attendance-decline", title: "Aman needs a trainer check-in", reason: "Training scenario: attendance has dropped for 12 days.", priority: "HIGH", recommendedAction: "Assign Trainer Ravi and agree a return-to-training plan.", assignedRole: "TRAINER", assignedUserId: trainer?.id, dueAt: new Date(Date.now() + 86400000), relatedState: "DECLINING", deduplicationKey: `${gymId}:training:aman:attention` }, update: { status: "OPEN", resolution: null, resolvedAt: null, dueAt: new Date(Date.now() + 86400000) } }); return aman; }
async function progressFor(userId: string, scenarioId: string) { return db.trainingProgress.findUnique({ where: { userId_scenarioId: { userId, scenarioId } } }); }
async function validate(user: Awaited<ReturnType<typeof requireUser>>, scenarioId: string, step: number) {
  const scenario = scenarioFor(scenarioId); const rule = scenario?.steps[step]?.validation; if (!rule) return true;
  const aman = await db.member.findFirst({ where: { gymId: user.gymId, fullName: { contains: "Aman", mode: "insensitive" } } });
  if (rule === "attention") return Boolean(aman && await db.attentionItem.findFirst({ where: { gymId: user.gymId, memberId: aman.id, status: { in: ["OPEN", "ASSIGNED", "IN_PROGRESS"] } } }));
  if (rule === "intervention") return Boolean(aman && await db.intervention.findFirst({ where: { gymId: user.gymId, memberId: aman.id } }));
  if (rule === "outcome") return Boolean(aman && await db.outcome.findFirst({ where: { gymId: user.gymId, memberId: aman.id } }));
  if (rule === "feedback") { const member = await db.member.findFirst({ where: { gymId: user.gymId, userId: user.id } }); return Boolean(member && await db.memberFeedback.findFirst({ where: { gymId: user.gymId, memberId: member.id } })); }
  if (rule === "group") { const member = await db.member.findFirst({ where: { gymId: user.gymId, userId: user.id } }); return Boolean(member && await db.groupMembership.findFirst({ where: { memberId: member.id, status: "ACTIVE" } })); }
  return Boolean(await db.visitor.findFirst({ where: { gymId: user.gymId, status: "ARRIVED" } }));
}

export async function startTraining(formData: FormData) {
  const user = await requireUser("dashboard:view"); await ensureTrainingRecords(user.gymId); const scenarioId = String(formData.get("scenarioId") ?? ""); const scenario = scenarioFor(scenarioId);
  if (!scenario || !canUseScenario(user.role as never, scenario)) redirect("/forbidden");
  const progress = await db.trainingProgress.upsert({ where: { userId_scenarioId: { userId: user.id, scenarioId } }, create: { gymId: user.gymId, userId: user.id, scenarioId, role: user.role, status: "ACTIVE", startedAt: new Date() }, update: { status: "ACTIVE", completedAt: null, startedAt: new Date() } });
  await db.trainingEvent.create({ data: { gymId: user.gymId, userId: user.id, scenarioId, eventType: "STARTED", stepIndex: progress.stepIndex } }); await audit({ gymId: user.gymId, actorId: user.id, action: "TRAINING_STARTED", entityType: "TrainingProgress", entityId: progress.id, after: { scenarioId } }); refresh(); redirect("/training");
}
export async function advanceTrainingStep(formData: FormData) {
  const user = await requireUser("dashboard:view"); await ensureTrainingRecords(user.gymId); const scenarioId = String(formData.get("scenarioId") ?? ""); const scenario = scenarioFor(scenarioId); const progress = await progressFor(user.id, scenarioId);
  if (!scenario || !progress || !canUseScenario(user.role as never, scenario)) redirect("/forbidden");
  if (!(await validate(user, scenarioId, progress.stepIndex))) redirect(`/training?scenario=${scenarioId}&notice=Complete+the+guided+action+first.`);
  const done = progress.stepIndex >= scenario.steps.length - 1; const nextIndex = done ? progress.stepIndex : progress.stepIndex + 1;
  await db.trainingProgress.update({ where: { id: progress.id }, data: { stepIndex: nextIndex, completedSteps: done ? scenario.steps.length : Math.max(progress.completedSteps, nextIndex), status: done ? "COMPLETED" : "ACTIVE", completedAt: done ? new Date() : null } });
  await db.trainingEvent.create({ data: { gymId: user.gymId, userId: user.id, scenarioId, eventType: done ? "COMPLETED" : "STEP_COMPLETED", stepIndex: progress.stepIndex } }); refresh(); redirect(`/training?scenario=${scenarioId}${done ? "&complete=1" : ""}`);
}
export async function previousTrainingStep(formData: FormData) { const user = await requireUser("dashboard:view"); await ensureTrainingRecords(user.gymId); const scenarioId = String(formData.get("scenarioId") ?? ""); const progress = await progressFor(user.id, scenarioId); if (!progress) redirect("/training"); await db.trainingProgress.update({ where: { id: progress.id }, data: { stepIndex: Math.max(0, progress.stepIndex - 1) } }); refresh(); redirect(`/training?scenario=${scenarioId}`); }
export async function skipTrainingStep(formData: FormData) { const user = await requireUser("dashboard:view"); await ensureTrainingRecords(user.gymId); const scenarioId = String(formData.get("scenarioId") ?? ""); const scenario = scenarioFor(scenarioId); const progress = await progressFor(user.id, scenarioId); if (!scenario || !progress) redirect("/training"); const done = progress.stepIndex >= scenario.steps.length - 1; await db.trainingProgress.update({ where: { id: progress.id }, data: { stepIndex: done ? progress.stepIndex : progress.stepIndex + 1, skippedSteps: progress.skippedSteps + 1, completedSteps: done ? scenario.steps.length : Math.max(progress.completedSteps, progress.stepIndex + 1), status: done ? "COMPLETED" : "ACTIVE", completedAt: done ? new Date() : null } }); await db.trainingEvent.create({ data: { gymId: user.gymId, userId: user.id, scenarioId, eventType: "SKIPPED", stepIndex: progress.stepIndex } }); refresh(); redirect(`/training?scenario=${scenarioId}${done ? "&complete=1" : ""}`); }
export async function exitTraining(formData: FormData) { const user = await requireUser("dashboard:view"); await ensureTrainingRecords(user.gymId); const scenarioId = String(formData.get("scenarioId") ?? ""); const progress = await progressFor(user.id, scenarioId); if (progress) await db.trainingProgress.update({ where: { id: progress.id }, data: { status: "PAUSED" } }); refresh(); redirect("/training"); }
export async function resetTrainingData() { const user = await requireUser("members:manage"); if (!["OWNER", "MANAGER"].includes(user.role)) redirect("/forbidden"); const interventions = await db.intervention.findMany({ where: { gymId: user.gymId, deduplicationKey: { startsWith: `${user.gymId}:training:` } }, select: { id: true } }); await db.outcome.deleteMany({ where: { interventionId: { in: interventions.map((item) => item.id) } } }); await db.intervention.deleteMany({ where: { id: { in: interventions.map((item) => item.id) } } }); await db.attentionItem.deleteMany({ where: { gymId: user.gymId, deduplicationKey: { startsWith: `${user.gymId}:training:` } } }); await db.trainingEvent.deleteMany({ where: { gymId: user.gymId } }); await db.trainingProgress.deleteMany({ where: { gymId: user.gymId } }); await ensureTrainingRecords(user.gymId); await audit({ gymId: user.gymId, actorId: user.id, action: "TRAINING_RESET", entityType: "Gym", entityId: user.gymId }); refresh(); redirect("/training?notice=Training+progress+and+scenario+records+were+reset.+Operational+demo+data+was+not+changed."); }
