import { notFound } from "next/navigation";
import { reportDiscomfort, submitFeedback } from "@/app/actions/experience";
import { DsBadge, DsButton, DsCard, DsInput, DsSelect, DsTextarea, Field } from "@/components/design-system";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { assertMemberAccess } from "@/lib/members";

const label = (value: string) => value.replaceAll("_", " ");
const tone = (value: string) => value === "CRITICAL" || value === "HIGH" || value === "NEGATIVE" || value === "ESCALATED" ? "danger" : value === "POSITIVE" || value === "RESOLVED" ? "success" : "warning" as const;
export default async function MemberExperiencePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const user = await requireUser();
  try { await assertMemberAccess(user, id, false); } catch { notFound(); }
  const sensitive = ["OWNER", "MANAGER"].includes(user.role);
  const member = await db.member.findFirst({ where: { id, gymId: user.gymId }, include: { attentionPreference: true, feedbacks: { where: sensitive || user.role === "MEMBER" ? {} : { confidential: false, feedbackType: { not: "TRAINER" } }, orderBy: { createdAt: "desc" }, take: 20 }, complaints: { where: sensitive || user.role === "MEMBER" ? {} : { category: { notIn: ["TRAINER", "SAFETY"] } }, orderBy: { createdAt: "desc" }, take: 20 }, discomfortReports: { orderBy: { dateReported: "desc" }, take: 10 } } });
  if (!member) notFound(); const isMember = user.role === "MEMBER"; const canWrite = ["OWNER", "MANAGER", "TRAINER", "MEMBER"].includes(user.role);
  return <><header className="page-header"><div><p className="eyebrow">Member experience</p><h1>{member.fullName}</h1><p>{isMember ? "Share feedback privately with the gym team, or note a discomfort for your trainer to follow up." : "Review preferences, feedback, complaints, and safe training modifications."}</p></div><a className="button button-outline" href={`/members/${member.id}`}>Member profile</a></header>
    <section className="detail-grid"><DsCard><h2 className="section-title">Fast feedback</h2><p className="small">How was your most recent gym experience?</p>{canWrite && <form action={submitFeedback} className="stack-form"><input type="hidden" name="memberId" value={member.id}/><Field label="Feedback type"><DsSelect name="feedbackType" defaultValue="GENERAL"><option>GENERAL</option><option>TRAINER</option><option>EQUIPMENT</option><option>CLEANLINESS</option><option>SAFETY</option><option>PAIN_DISCOMFORT</option></DsSelect></Field><div className="rating-actions" aria-label="Rating"><button className="rating-button rating-great" name="rating" value="4">Great</button><button className="rating-button rating-good" name="rating" value="3">Good</button><button className="rating-button rating-okay" name="rating" value="2">Okay</button><button className="rating-button rating-poor" name="rating" value="1">Poor</button></div><Field label="Main reason"><DsSelect name="primaryReason" defaultValue=""><option value="">Choose a reason</option><option>Great coaching</option><option>Helpful staff</option><option>Equipment broken</option><option>Gym was crowded</option><option>Felt uncomfortable</option><option>Trainer issue</option><option>Pain/discomfort</option></DsSelect></Field><Field label="Anything else? (optional)"><DsTextarea name="freeText" placeholder="Share only what helps the team improve."/></Field>{isMember && <label className="check-control"><input type="checkbox" name="confidential"/><span>Keep this confidential from trainers</span></label>}<DsButton>Send feedback</DsButton></form>}</DsCard>
      <DsCard><h2 className="section-title">Attention preferences</h2><p><strong>{label(member.attentionPreference?.level ?? "OCCASIONAL_CHECK_IN")}</strong></p><p className="small">Preferred contact: {label(member.attentionPreference?.contactMethod ?? "IN_PERSON")}{member.attentionPreference?.noInterruption ? " · no interruption during workout" : ""}</p><a className="button button-outline button-sm" href={`/members/${member.id}`}>Update preferences</a><h3 className="subsection-title">Current feedback</h3>{member.feedbacks.length ? <div className="list">{member.feedbacks.map(item => <div className="list-item" key={item.id}><span><strong>{label(item.feedbackType)}</strong><br/><span className="small">{item.primaryReason ?? "No reason selected"} · {item.createdAt.toLocaleDateString("en-IN")}</span></span><DsBadge tone={tone(item.sentiment)}>{item.sentiment}</DsBadge></div>)}</div> : <p className="small">No feedback recorded yet.</p>}</DsCard></section>
    <section className="detail-grid"><DsCard><h2 className="section-title">Pain or discomfort</h2><p className="small">This is not medical advice. Record a training concern so the trainer can agree a safe temporary modification and follow up.</p>{canWrite && <form action={reportDiscomfort} className="stack-form"><input type="hidden" name="memberId" value={member.id}/><Field label="Body area"><DsInput name="bodyArea" required placeholder="For example: right shoulder"/></Field><Field label="Severity"><DsSelect name="severity" defaultValue="LOW"><option>LOW</option><option>MEDIUM</option><option>HIGH</option></DsSelect></Field><Field label="What happened?"><DsTextarea name="description" required placeholder="Describe the discomfort in your own words."/></Field><Field label="Exercise or movement (optional)"><DsInput name="triggeringExercise" placeholder="For example: overhead press"/></Field><Field label="Agreed temporary modification (optional)"><DsInput name="temporaryModification" placeholder="For example: avoid overhead presses"/></Field><DsButton variant="outline">Record and schedule follow-up</DsButton></form>}</DsCard>
      <DsCard><h2 className="section-title">Open issues & follow-ups</h2>{member.complaints.length ? <div className="list">{member.complaints.map(item => <div className="list-item" key={item.id}><div><strong>{label(item.category)}</strong><p className="small">{item.description}</p><p className="small">{item.resolution ? `Resolution: ${item.resolution}` : "Awaiting a recorded resolution"}</p></div><DsBadge tone={tone(item.status === "RESOLVED" ? "RESOLVED" : item.severity)}>{item.status}</DsBadge></div>)}</div> : <p className="small">No complaint records visible to this role.</p>}<h3 className="subsection-title">Discomfort history</h3>{member.discomfortReports.length ? <div className="list">{member.discomfortReports.map(item => <div className="list-item" key={item.id}><div><strong>{item.bodyArea}</strong><p className="small">{item.description} · follow-up {item.followUpDate?.toLocaleDateString("en-IN")}</p></div><DsBadge tone={tone(item.severity)}>{item.status}</DsBadge></div>)}</div> : <p className="small">No discomfort reports recorded.</p>}</DsCard></section>
  </>;
}
