import { resetTrainingData, startTraining } from "@/app/actions/training";
import { TrainingGuide } from "@/components/training-guide";
import { DsBadge, DsCard } from "@/components/design-system";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { canUseScenario, scenarioFor, trainingScenarios } from "@/lib/training";

type Search = Promise<{ scenario?: string; notice?: string; complete?: string }>;
export default async function TrainingPage({ searchParams }: { searchParams: Search }) {
  const user = await requireUser("dashboard:view"); const query = await searchParams;
  const progress = await db.trainingProgress.findMany({ where: { userId: user.id }, orderBy: { updatedAt: "desc" } });
  const active = progress.find((item) => item.status === "ACTIVE"); const selected = scenarioFor(query.scenario ?? active?.scenarioId ?? ""); const selectedProgress = selected ? progress.find((item) => item.scenarioId === selected.id) : undefined;
  const available = trainingScenarios.filter((scenario) => canUseScenario(user.role as never, scenario)); const complete = progress.filter((item) => item.status === "COMPLETED").length;
  return <><header className="page-header"><div><p className="eyebrow">DEMO TRAINING MODE</p><h1>Training Center</h1><p>Practice realistic workflows in short guided steps. Training never changes your permissions.</p></div><DsBadge tone="info">{complete}/{available.length} complete</DsBadge></header>{query.notice && <p className="training-notice">{query.notice}</p>}{query.complete && selected && <DsCard className="training-complete"><p className="eyebrow">TRAINING COMPLETE</p><h2>{selected.title}</h2><p>You completed {selected.steps.length} steps and practiced the core workflow. Next recommended: {scenarioFor(selected.next ?? "")?.title ?? "another role scenario"}.</p></DsCard>}{selected && selectedProgress?.status === "ACTIVE" && <TrainingGuide scenario={selected} stepIndex={selectedProgress.stepIndex}/>}<section className="training-grid">{available.map((scenario) => { const item = progress.find((entry) => entry.scenarioId === scenario.id); const done = item?.status === "COMPLETED"; const percent = item ? Math.round((item.completedSteps / scenario.steps.length) * 100) : 0; return <DsCard className="training-card" key={scenario.id}><div className="card-heading"><div><p className="eyebrow">{scenario.role === "FULL" ? "CROSS-ROLE" : scenario.role}</p><h2>{scenario.title}</h2></div>{done && <DsBadge tone="success">COMPLETE</DsBadge>}</div><p>{scenario.description}</p><p className="small">{scenario.estimate} steps · {percent}% complete{item?.skippedSteps ? ` · ${item.skippedSteps} skipped` : ""}</p><div className="training-progress"><span style={{ width: `${percent}%` }}/></div><form action={startTraining}><input type="hidden" name="scenarioId" value={scenario.id}/><button className="button button-primary">{item && !done ? "Continue" : done ? "Start again" : "Start training"}</button></form></DsCard>; })}</section><section className="detail-grid"><DsCard><h2 className="section-title">Learning checklist</h2><div className="training-checklist">{["Understand member states", "Review an attention item", "Create or start intervention work", "Measure an outcome", "Use your role’s daily workspace"].map((item, index) => <label key={item}><input type="checkbox" checked={complete > index || progress.some((entry) => entry.completedSteps > index)} readOnly/><span>{item}</span></label>)}</div></DsCard><DsCard><h2 className="section-title">Reset training data</h2><p className="small">Resets only saved training progress and training analytics. It does not alter members, interventions, visits, or other operational demo data.</p>{["OWNER", "MANAGER"].includes(user.role) ? <form action={resetTrainingData}><button className="button button-outline">Reset Training Data</button></form> : <p className="small">Only an Owner or Manager can reset training progress.</p>}</DsCard></section></>;
}
