import { notFound, redirect } from "next/navigation";
import { resolveComplaint } from "@/app/actions/experience";
import { DsBadge, DsButton, DsCard, DsInput, DsSelect, DsTextarea, Field, StatCard } from "@/components/design-system";
import { requireRole } from "@/lib/auth";
import { db } from "@/lib/db";

type Search = Promise<{ q?: string; sentiment?: string; category?: string; severity?: string; status?: string }>;
const label = (value: string) => value.replaceAll("_", " ");
const badgeTone = (value: string) => value === "CRITICAL" || value === "HIGH" || value === "NEGATIVE" || value === "ESCALATED" ? "danger" : value === "POSITIVE" || value === "RESOLVED" ? "success" : "warning" as const;

export default async function ExperiencePage({ searchParams }: { searchParams: Search }) {
  const user = await requireRole(["OWNER", "MANAGER", "TRAINER", "RECEPTION"]);
  if (user.role === "MEMBER") { const member = await db.member.findFirst({ where: { gymId: user.gymId, userId: user.id }, select: { id: true } }); if (!member) notFound(); redirect(`/members/${member.id}/experience`); }
  const f = await searchParams;
  const memberWhere = user.role === "TRAINER" ? { trainerId: user.id, ...(f.q ? { fullName: { contains: f.q, mode: "insensitive" as const } } : {}) } : f.q ? { fullName: { contains: f.q, mode: "insensitive" as const } } : undefined;
  const memberScope = memberWhere ? { member: memberWhere } : {};
  const receptionFeedback = user.role === "RECEPTION" ? { confidential: false, feedbackType: { notIn: ["TRAINER", "SAFETY", "PAIN_DISCOMFORT"] } } : {};
  const receptionComplaint = user.role === "RECEPTION" ? { category: { in: ["EQUIPMENT", "CLEANLINESS", "SCHEDULE", "GENERAL"] } } : {};
  const feedbackWhere = { gymId: user.gymId, ...memberScope, ...receptionFeedback, ...(f.sentiment ? { sentiment: f.sentiment } : {}), ...(f.category ? { feedbackType: f.category } : {}) };
  const complaintWhere = { gymId: user.gymId, ...memberScope, ...receptionComplaint, ...(f.severity ? { severity: f.severity } : {}), ...(f.status ? { status: f.status } : {}) };
  const [feedback, complaints, discomfort] = await Promise.all([
    db.memberFeedback.findMany({ where: feedbackWhere, include: { member: { select: { fullName: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
    db.complaint.findMany({ where: complaintWhere, include: { member: { select: { fullName: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
    db.discomfortReport.findMany({ where: { gymId: user.gymId, ...memberScope, status: "ACTIVE" }, include: { member: { select: { fullName: true } } }, orderBy: { followUpDate: "asc" }, take: 50 }),
  ]);
  const canManage = ["OWNER", "MANAGER"].includes(user.role);
  return <>
    <header className="page-header"><div><p className="eyebrow">Member experience</p><h1>Feedback & escalations</h1><p>Operational feedback, complaints, and non-medical discomfort follow-ups — all persisted and visible to the right role.</p></div></header>
    <section className="stat-grid"><StatCard label="Feedback received" value={feedback.length} note="Filtered, database-backed responses"/><StatCard label="Negative feedback" value={feedback.filter(item => item.sentiment === "NEGATIVE").length} note="Requires review when repeated"/><StatCard label="Open complaints" value={complaints.filter(item => item.status !== "RESOLVED").length} note="No complaint closes silently"/><StatCard label="Active discomfort" value={discomfort.length} note="Trainer follow-up is scheduled"/></section>
    <form className="filter-bar" action="/experience"><DsInput name="q" defaultValue={f.q} placeholder="Search member"/><DsSelect name="sentiment" defaultValue={f.sentiment ?? ""}><option value="">All sentiment</option><option>POSITIVE</option><option>NEUTRAL</option><option>NEGATIVE</option></DsSelect><DsSelect name="category" defaultValue={f.category ?? ""}><option value="">All feedback types</option><option>GENERAL</option><option>TRAINER</option><option>EQUIPMENT</option><option>SAFETY</option><option>PAIN_DISCOMFORT</option></DsSelect>{user.role !== "RECEPTION" && <DsSelect name="severity" defaultValue={f.severity ?? ""}><option value="">All severities</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></DsSelect>}<DsSelect name="status" defaultValue={f.status ?? ""}><option value="">All complaint states</option><option>OPEN</option><option>ESCALATED</option><option>RESOLVED</option></DsSelect><DsButton variant="outline">Filter</DsButton></form>
    <section className="detail-grid"><DsCard><h2 className="section-title">Experience review queue</h2>{feedback.length ? <div className="list">{feedback.map(item => <article className="list-item" key={item.id}><div><a className="member-link" href={`/members/${item.memberId}/experience`}><strong>{item.member.fullName}</strong><span>{label(item.feedbackType)} · {item.rating}/4</span></a><p className="small">{item.primaryReason ?? item.freeText ?? "No additional detail"}</p><p className="small">{item.createdAt.toLocaleString("en-IN")}{item.confidential ? " · confidential" : ""}</p></div><DsBadge tone={badgeTone(item.sentiment)}>{item.sentiment}</DsBadge></article>)}</div> : <p className="empty-state"><strong>No feedback matches</strong><br/>Member responses will appear here after a check-in or visit prompt.</p>}</DsCard>
      <DsCard><h2 className="section-title">Complaint & escalation queue</h2>{complaints.length ? <div className="list">{complaints.map(item => <article className="trainer-work-item" key={item.id}><div><a className="member-link" href={`/members/${item.memberId}/experience`}><strong>{item.member.fullName}</strong><span>{label(item.category)} · opened {item.createdAt.toLocaleDateString("en-IN")}</span></a><p className="small">{item.description}</p><div className="badge-row"><DsBadge tone={badgeTone(item.severity)}>{item.severity}</DsBadge><DsBadge tone={badgeTone(item.status)}>{item.status}</DsBadge></div></div>{canManage && item.status !== "RESOLVED" && <form action={resolveComplaint} className="stack-form"><input type="hidden" name="complaintId" value={item.id}/><Field label="Resolution"><DsTextarea name="resolution" required placeholder="What was agreed and completed?"/></Field><Field label="Follow-up date (optional)"><DsInput type="date" name="followUpDate"/></Field><DsButton size="sm">Resolve with record</DsButton></form>}</article>)}</div> : <p className="empty-state"><strong>No complaints match</strong><br/>Safety and trainer concerns are escalated automatically.</p>}</DsCard></section>
    <DsCard><h2 className="section-title">Active discomfort follow-ups</h2>{discomfort.length ? <div className="list">{discomfort.map(item => <article className="list-item" key={item.id}><div><a className="member-link" href={`/members/${item.memberId}/experience`}><strong>{item.member.fullName}</strong><span>{item.bodyArea} · follow-up {item.followUpDate?.toLocaleDateString("en-IN")}</span></a><p className="small">{item.description}{item.temporaryModification ? ` · Temporary modification: ${item.temporaryModification}` : ""}</p></div><DsBadge tone={badgeTone(item.severity)}>{item.severity}</DsBadge></article>)}</div> : <p className="empty-state"><strong>No active discomfort reports</strong><br/>This is non-medical tracking with an assigned trainer check-in.</p>}</DsCard>
  </>;
}
