import { notFound } from "next/navigation";
import { evaluateOutcome } from "@/app/actions/outcomes";
import { DsBadge, DsButton, DsCard, DsInput, DsSelect, DsTextarea, Field } from "@/components/design-system";
import { requireUser } from "@/lib/auth";
import { suggestOutcome, outcomeStatuses } from "@/lib/outcomes";

type Params = Promise<{ id: string }>;
const label = (value: string) => value.replaceAll("_", " ");
export default async function OutcomeEvaluation({ params }: { params: Params }) {
  const user = await requireUser("members:view"); if (user.role === "MEMBER") notFound(); const { id } = await params; const suggestion = await suggestOutcome(id, user.gymId); const item = suggestion.intervention; if (user.role === "TRAINER" && item.assignedToId !== user.id) notFound(); const existing = await (await import("@/lib/db")).db.outcome.findUnique({ where: { interventionId: item.id } }); const canEvaluate = ["OWNER", "MANAGER", "TRAINER"].includes(user.role);
  return <><header className="page-header"><div><p className="eyebrow">Outcome evaluation</p><h1>{item.member.fullName}</h1><p>{item.title} · evaluation window ends {suggestion.end.toLocaleDateString("en-IN")}</p></div><DsBadge tone={suggestion.suggestedStatus === "IMPROVED" ? "success" : suggestion.suggestedStatus === "DECLINED" ? "danger" : "warning"}>Suggested: {label(suggestion.suggestedStatus)}</DsBadge></header><section className="detail-grid"><DsCard><h2 className="section-title">Original problem</h2><p>{item.reason}</p><p className="small">State: {item.member.memberState} · Created {item.createdAt.toLocaleDateString("en-IN")}</p><p className="small"><strong>Metric to check:</strong> {label(suggestion.template.metric)}</p></DsCard><DsCard><h2 className="section-title">Action taken</h2><p>{item.actionTaken ?? "No action text recorded."}</p><p className="small">Type: {label(item.type)} · Completed {item.completedAt?.toLocaleDateString("en-IN") ?? "Not recorded"}</p><p className="small">Notes: {item.notes ?? "—"}</p></DsCard></section><section className="detail-grid"><DsCard><h2 className="section-title">Before snapshot</h2><pre className="snapshot">{JSON.stringify(suggestion.before, null, 2)}</pre></DsCard><DsCard><h2 className="section-title">After snapshot</h2><pre className="snapshot">{JSON.stringify(suggestion.after, null, 2)}</pre><p className="small">{suggestion.explanation}</p></DsCard></section>{canEvaluate && <DsCard><h2 className="section-title">Staff decision</h2><p className="small">The suggestion is calculated from real persisted data. Confirm it or select a more accurate result with an explanation.</p><form action={evaluateOutcome} className="form-grid"><input type="hidden" name="interventionId" value={item.id}/><Field label="Outcome"><DsSelect name="outcomeStatus" defaultValue={existing?.outcomeStatus ?? suggestion.suggestedStatus}>{outcomeStatuses.map((status) => <option value={status} key={status}>{label(status)}</option>)}</DsSelect></Field><Field label="Explanation"><DsTextarea name="notes" defaultValue={existing?.notes ?? ""} placeholder="Why is this the right result?"/></Field><Field label="Next action"><DsTextarea name="nextAction" defaultValue={existing?.nextAction ?? ""} placeholder="Required for unchanged, declined, or insufficient data"/></Field>{user.role !== "TRAINER" && <><Field label="Recorded business impact"><DsSelect name="businessImpactType" defaultValue={existing?.businessImpactType ?? ""}><option value="">None</option><option>RENEWAL_RETAINED</option><option>PT_SALE</option><option>MEMBERSHIP_RECOVERED</option><option>OTHER</option></DsSelect></Field><Field label="Associated value (₹)"><DsInput name="businessImpactValue" type="number" min="0" defaultValue={existing?.businessImpactValue ?? ""}/></Field></>}<div className="form-actions"><DsButton type="submit">Confirm outcome</DsButton><a className="button button-outline" href="/outcomes">Back to outcomes</a></div></form></DsCard>}</>;
}
