"use client";

import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes, TextareaHTMLAttributes } from "react";
import { LoaderCircle, Search, X } from "lucide-react";
import { cn } from "@/lib/utils";

type Tone = "neutral" | "success" | "warning" | "danger" | "info";
export function DsButton({ children, className, variant = "primary", size = "md", loading, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "outline" | "ghost" | "danger" | "icon"; size?: "sm" | "md" | "lg"; loading?: boolean }) { return <button className={cn("button", `button-${variant}`, `button-${size}`, className)} disabled={loading || props.disabled} {...props}>{loading && <LoaderCircle className="spin" size={16}/>} {children}</button>; }
export function DsInput({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={cn("input", className)} {...props} />; }
export function DsTextarea({ className, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className={cn("textarea", className)} {...props} />; }
export function Field({ label, hint, error, children }: { label: string; hint?: string; error?: string; children: ReactNode }) { return <label className="field"><span className="field-label">{label}</span>{children}{error ? <span className="field-error" role="alert">{error}</span> : hint ? <span className="field-hint">{hint}</span> : null}</label>; }
export function DsSelect({ children, className, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { children: ReactNode }) { return <select className={cn("input", "select", className)} {...props}>{children}</select>; }
export function Checkbox({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="check-control"><input type="checkbox" {...props}/><span>{label}</span></label>; }
export function Radio({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="check-control"><input type="radio" {...props}/><span>{label}</span></label>; }
export function Toggle({ label, checked, onChange, disabled }: { label: string; checked: boolean; onChange?: (value: boolean) => void; disabled?: boolean }) { return <label className="toggle"><span>{label}</span><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange?.(event.target.checked)}/><span className="toggle-track" aria-hidden="true"/></label>; }
export function Tabs({ tabs, active, onChange }: { tabs: Array<{ id: string; label: string }>; active: string; onChange: (id: string) => void }) { return <div className="tabs" role="tablist">{tabs.map((tab) => <button type="button" role="tab" aria-selected={active === tab.id} className={cn("tab", active === tab.id && "active")} onClick={() => onChange(tab.id)} key={tab.id}>{tab.label}</button>)}</div>; }
export function DsBadge({ children, tone = "neutral" }: { children: ReactNode; tone?: Tone }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
export function DsCard({ children, className }: { children: ReactNode; className?: string }) { return <section className={cn("card", className)}>{children}</section>; }
export function StatCard({ label, value, note, icon }: { label: string; value: ReactNode; note?: string; icon?: ReactNode }) { return <DsCard><div className="stat-heading"><p className="stat-label">{label}</p>{icon}</div><p className="stat-value">{value}</p>{note && <p className="stat-note">{note}</p>}</DsCard>; }
export function Avatar({ name, size = "md" }: { name: string; size?: "sm" | "md" | "lg" }) { return <span className={cn("avatar", `avatar-${size}`)} aria-label={name}>{name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span>; }
export function DataTable({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn("table-wrap", className)}><table className="table">{children}</table></div>; }
export function Pagination({ page, totalPages, onPageChange }: { page: number; totalPages: number; onPageChange: (page: number) => void }) { return <nav className="pagination" aria-label="Pagination"><DsButton variant="outline" size="sm" disabled={page <= 1} onClick={() => onPageChange(page - 1)}>Previous</DsButton><span>Page {page} of {Math.max(totalPages, 1)}</span><DsButton variant="outline" size="sm" disabled={page >= totalPages} onClick={() => onPageChange(page + 1)}>Next</DsButton></nav>; }
export function SearchField({ value, onChange, placeholder = "Search" }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="search-field"><Search size={17}/><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} aria-label={placeholder}/>{value && <button type="button" aria-label="Clear search" onClick={() => onChange("")}><X size={15}/></button>}</label>; }
export function FilterBar({ children }: { children: ReactNode }) { return <div className="filter-bar" aria-label="Filters">{children}</div>; }
export function Tooltip({ label, children }: { label: string; children: ReactNode }) { return <span className="tooltip" tabIndex={0}>{children}<span role="tooltip">{label}</span></span>; }
export function Popover({ label, children }: { label: string; children: ReactNode }) { return <details className="popover"><summary>{label}</summary><div>{children}</div></details>; }
export function Dialog({ title, children, open = true }: { title: string; children: ReactNode; open?: boolean }) { if (!open) return null; return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-label={title}><h2>{title}</h2>{children}</section></div>; }
export function Drawer({ title, children, open = true }: { title: string; children: ReactNode; open?: boolean }) { if (!open) return null; return <aside className="component-drawer" aria-label={title}><h2>{title}</h2>{children}</aside>; }
export function Toast({ children, tone = "success" }: { children: ReactNode; tone?: Tone }) { return <div className={`toast toast-${tone}`} role="status">{children}</div>; }
export function Skeleton({ lines = 3 }: { lines?: number }) { return <div className="skeleton" aria-label="Loading">{Array.from({ length: lines }, (_, index) => <span key={index}/>)}</div>; }
export function DsEmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="empty-state"><strong>{title}</strong><p>{description}</p>{action}</div>; }
export function ErrorState({ title = "Something went wrong", description, action }: { title?: string; description: string; action?: ReactNode }) { return <div className="error-state" role="alert"><strong>{title}</strong><p>{description}</p>{action}</div>; }
export function ConfirmDialog({ title, description, onConfirm, onCancel }: { title: string; description: string; onConfirm: () => void; onCancel: () => void }) { return <Dialog title={title}><p>{description}</p><div className="dialog-actions"><DsButton variant="outline" onClick={onCancel}>Cancel</DsButton><DsButton variant="danger" onClick={onConfirm}>Confirm</DsButton></div></Dialog>; }
