import { db } from "@/lib/db";
import { evaluateAttendance, evaluateMembership, evaluateOnboarding, evaluateProgress, evaluatePtOpportunity, evaluateTrainerInteraction, type RuleResult } from "@/lib/intelligence";

const DAY = 86_400_000;
const rank: Record<string, number> = { LAPSED: 7, AT_RISK: 6, WIN_BACK: 5, DECLINING: 4, PLATEAU: 3, ONBOARDING: 2, ADVANCING: 1 };
const automaticTypes: Record<string, string> = { "attendance-14-day": "PERSONAL_OUTREACH", "onboarding-assessment": "WELCOME_CHECK_IN", "onboarding-first-visit": "WELCOME_CHECK_IN", "onboarding-low-visits": "WELCOME_CHECK_IN", "trainer-interaction-gap": "TRAINER_CHECK_IN", "progress-plateau": "PROGRAM_REASSESSMENT", "review-overdue": "PROGRAM_REASSESSMENT" };
export async function runIntelligenceV2(gymId: string) {
  const now = Date.now(); let triggered = 0; let created = 0; const active = new Set<string>();
  const members = await db.member.findMany({ where:{gymId}, include:{ visits:{select:{visitedAt:true}}, assessments:{select:{assessedAt:true}}, reviews:{select:{nextReviewDate:true},orderBy:{reviewedAt:"desc"},take:1}, goals:{where:{status:"ACTIVE"},select:{isPrimary:true,startingValue:true,targetValue:true,type:true}}, metrics:{select:{recordedAt:true,type:true,value:true},orderBy:{recordedAt:"desc"}}, memberships:{select:{planName:true,status:true}}, activities:{select:{createdAt:true,actorId:true},orderBy:{createdAt:"desc"},take:1} } });
  for (const member of members) {
    const daysSinceVisit = Math.floor((now-(member.lastVisit?.getTime() ?? member.joinDate.getTime()))/DAY);
    const recent = member.visits.filter(v=>v.visitedAt.getTime()>=now-28*DAY).length/4;
    const baseline = member.visits.filter(v=>v.visitedAt.getTime()<now-28*DAY && v.visitedAt.getTime()>=now-56*DAY).length/4;
    const primary = member.goals.find(g=>g.isPrimary) ?? member.goals[0];
    const targetType = primary?.type === "STRENGTH" ? "SQUAT" : primary?.type;
    const latest = targetType ? member.metrics.find(m=>m.type===targetType) : undefined;
    const start = primary?.startingValue ? Number(primary.startingValue) : null; const target = primary?.targetValue ? Number(primary.targetValue) : null; const current = latest ? Number(latest.value) : null;
    const progress = start !== null && target !== null && current !== null && start !== target ? Math.max(0,Math.min(100,((current-start)/(target-start))*100)) : null;
    const lastMetric = latest?.recordedAt?.getTime() ?? 0; const reviewDue = member.reviews[0]?.nextReviewDate?.getTime() ?? 0;
    const results: RuleResult[] = [...evaluateAttendance({daysSinceVisit,baselineVisits:baseline,currentVisits:recent}), ...evaluateMembership(Math.floor((member.membershipEnd.getTime()-now)/DAY)), ...evaluateOnboarding({daysSinceJoin:Math.floor((now-member.joinDate.getTime())/DAY),visits:member.visits.length,hasAssessment:member.assessments.length>0}), ...evaluateProgress({daysSinceMetric:lastMetric ? Math.floor((now-lastMetric)/DAY) : 999,reviewOverdue:reviewDue>0 && reviewDue<now,goalProgress:progress,goalCompleted:progress !== null && progress>=100}), ...evaluatePtOpportunity({consistent:recent>=2.5,hasPt:member.memberships.some(m=>m.planName.toLowerCase().includes("pt")),positiveProgress:progress !== null && progress>20}), ...evaluateTrainerInteraction(member.activities[0] ? Math.floor((now-member.activities[0].createdAt.getTime())/DAY) : 999)];
    let nextState = progress !== null && progress > 0 ? "PROGRESSING" : recent >= 1 ? "CONSISTENT" : "NEW"; let stateResult: RuleResult | undefined;
    for (const result of results) { if (result.state && (rank[result.state] ?? 0) >= (rank[nextState] ?? 0)) { nextState=result.state; stateResult=result; } const key=[gymId,member.id,result.ruleId].join(":"); active.add(key); triggered++; let attention=await db.attentionItem.findUnique({where:{deduplicationKey:key}}); if (!attention) { attention=await db.attentionItem.create({data:{gymId,memberId:member.id,ruleId:result.ruleId,title:result.title,reason:result.reason,priority:result.priority,recommendedAction:result.action,assignedRole:result.role,assignedUserId:result.role==="TRAINER" ? member.trainerId : null,dueAt:new Date(now+result.dueDays*DAY),relatedState:result.state,deduplicationKey:key}}); created++; } else if (attention.status==="EXPIRED") attention=await db.attentionItem.update({where:{id:attention.id},data:{status:"OPEN",reason:result.reason,resolution:null,resolvedAt:null,dueAt:new Date(now+result.dueDays*DAY)}}); const type=automaticTypes[result.ruleId]; const interventionKey=[gymId,member.id,"auto",result.ruleId].join(":"); if (type && !await db.intervention.findUnique({where:{deduplicationKey:interventionKey}})) await db.intervention.create({data:{gymId,memberId:member.id,attentionItemId:attention.id,type,title:result.title,reason:result.reason,recommendedAction:result.action,priority:result.priority,assignedRole:member.trainerId ? "TRAINER" : result.role,assignedToId:member.trainerId,dueAt:new Date(now+result.dueDays*DAY),assignedAt:member.trainerId ? new Date(now) : null,status:member.trainerId ? "ASSIGNED" : "OPEN",deduplicationKey:interventionKey}}); }
    if (nextState!==member.memberState) { const reason=stateResult?.reason ?? "Current activity and measurable progress indicate a stable member pattern."; const priority=stateResult?.priority ?? "LOW"; await db.member.update({where:{id:member.id},data:{memberState:nextState,attentionLevel:priority}}); await db.memberStateHistory.create({data:{gymId,memberId:member.id,previousState:member.memberState,state:nextState,reason,source:stateResult?.ruleId ?? "baseline-state"}}); }
  }
  const resolved=await db.attentionItem.updateMany({where:{gymId,status:{in:["OPEN","ASSIGNED","IN_PROGRESS"]},NOT:{deduplicationKey:{in:[...active]}}},data:{status:"EXPIRED",resolution:"Condition no longer matches this member.",resolvedAt:new Date(now)}});
  return db.intelligenceRun.create({data:{gymId,membersEvaluated:members.length,rulesTriggered:triggered,newItems:created,resolvedItems:resolved.count}});
}
