export type Priority = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "OPPORTUNITY";
export type RuleResult = { ruleId: string; title: string; reason: string; priority: Priority; state?: string; action: string; role: string; dueDays: number };
export const intelligenceRules = { noVisitWarningDays: 7, noVisitRiskDays: 14, attendanceDecline: 0.4, strongAttendanceDecline: 0.6, plateauDays: 28, lapsedDays: 30, trainerInteractionDays: 21, renewalDays: 30 } as const;
export function evaluateAttendance(input: { daysSinceVisit: number; baselineVisits: number; currentVisits: number }): RuleResult[] {
  const results: RuleResult[] = []; const decline = input.baselineVisits > 0 ? 1 - input.currentVisits / input.baselineVisits : 0;
  if (input.daysSinceVisit >= intelligenceRules.noVisitRiskDays) results.push({ ruleId:"attendance-14-day", title:"Absent for 14 days", reason:"No recorded visit for 14 days.", priority:"HIGH", state:"AT_RISK", action:"Personal trainer/member outreach", role:"TRAINER", dueDays:0 });
  else if (input.daysSinceVisit >= intelligenceRules.noVisitWarningDays) results.push({ ruleId:"attendance-7-day", title:"Absent for 7 days", reason:"No recorded visit for 7 days.", priority:"MEDIUM", action:"Check in with member", role:"TRAINER", dueDays:2 });
  if (decline >= intelligenceRules.strongAttendanceDecline) results.push({ ruleId:"attendance-decline-60", title:"Attendance strongly declined", reason:"Attendance is down more than 60% against the member baseline.", priority:"HIGH", state:"AT_RISK", action:"Personal outreach and plan review", role:"TRAINER", dueDays:1 });
  else if (decline >= intelligenceRules.attendanceDecline) results.push({ ruleId:"attendance-decline-40", title:"Attendance declined", reason:"Attendance is down more than 40% against the member baseline.", priority:"HIGH", state:"DECLINING", action:"Trainer check-in", role:"TRAINER", dueDays:2 });
  if (input.daysSinceVisit >= intelligenceRules.lapsedDays) results.push({ ruleId:"attendance-lapsed", title:"Member is lapsed", reason:"No recorded visit for 30 days.", priority:"HIGH", state:"LAPSED", action:"Begin a respectful win-back conversation", role:"TRAINER", dueDays:1 });
  return results;
}
export function evaluateMembership(daysUntilExpiry: number): RuleResult[] { if (daysUntilExpiry < 0) return [{ ruleId:"membership-win-back", title:"Membership has lapsed", reason:"Membership has expired; a win-back conversation may be appropriate.", priority:"OPPORTUNITY", state:"WIN_BACK", action:"Offer a respectful return conversation", role:"RECEPTION", dueDays:7 }]; if (daysUntilExpiry <= 7) return [{ ruleId:"renewal-7-day", title:"Membership expires within 7 days", reason:"Membership expiry is within 7 days.", priority:"HIGH", action:"Renewal conversation", role:"RECEPTION", dueDays:0 }]; if (daysUntilExpiry <= intelligenceRules.renewalDays) return [{ ruleId:"renewal-30-day", title:"Renewal opportunity", reason:"Membership expires within 30 days.",priority:"OPPORTUNITY",action:"Discuss renewal options",role:"RECEPTION",dueDays:5 }]; return []; }
export function evaluateOnboarding(input: { daysSinceJoin: number; visits: number; hasAssessment: boolean }): RuleResult[] { const results: RuleResult[]=[]; if (input.daysSinceJoin <= 30 && !input.hasAssessment) results.push({ruleId:"onboarding-assessment",title:"Baseline assessment incomplete",reason:"New member has no baseline assessment.",priority:"HIGH",state:"ONBOARDING",action:"Complete baseline assessment",role:"TRAINER",dueDays:1}); if (input.daysSinceJoin >= 3 && input.daysSinceJoin <= 14 && input.visits === 0) results.push({ruleId:"onboarding-first-visit",title:"No first workout",reason:"New member has no recorded visit in the first 3 days.",priority:"HIGH",action:"Trainer follow-up",role:"TRAINER",dueDays:0}); if (input.daysSinceJoin >= 14 && input.visits < 2) results.push({ruleId:"onboarding-low-visits",title:"Early attendance is low",reason:"Member has fewer than 2 visits in the first 14 days.",priority:"HIGH",state:"AT_RISK",action:"Early onboarding intervention",role:"TRAINER",dueDays:1}); return results; }
export function evaluateProgress(input: { daysSinceMetric:number; reviewOverdue:boolean; goalProgress:number|null; goalCompleted:boolean }): RuleResult[] { const r:RuleResult[]=[]; if(input.daysSinceMetric>=intelligenceRules.plateauDays) r.push({ruleId:"progress-plateau",title:"Measurable progress is overdue",reason:"No matching measurable progress has been recorded for 4 weeks.",priority:"MEDIUM",state:"PLATEAU",action:"Program reassessment",role:"TRAINER",dueDays:3}); if(input.reviewOverdue) r.push({ruleId:"review-overdue",title:"Progress review overdue",reason:"The scheduled progress review date has passed.",priority:"MEDIUM",action:"Complete reassessment",role:"TRAINER",dueDays:2}); if(input.goalCompleted) r.push({ruleId:"goal-complete",title:"Goal completed",reason:"Primary goal progress reached 100%.",priority:"OPPORTUNITY",state:"ADVANCING",action:"Celebrate and define the next goal",role:"TRAINER",dueDays:7}); else if(input.goalProgress!==null && input.goalProgress>80) r.push({ruleId:"goal-advancing",title:"Goal is nearly complete",reason:"Primary goal progress is above 80%.",priority:"OPPORTUNITY",state:"ADVANCING",action:"Plan next-stage goal review",role:"TRAINER",dueDays:7}); return r; }
export function evaluatePtOpportunity(input:{consistent:boolean;hasPt:boolean;positiveProgress:boolean}):RuleResult[]{ return input.consistent&&!input.hasPt&&input.positiveProgress?[{ruleId:"pt-opportunity",title:"PT opportunity",reason:"Member is consistently active, progressing, and has no PT plan.",priority:"OPPORTUNITY",action:"Offer an optional PT consultation",role:"TRAINER",dueDays:14}]:[]; }
export function evaluateTrainerInteraction(daysSinceInteraction: number): RuleResult[] { return daysSinceInteraction >= intelligenceRules.trainerInteractionDays ? [{ ruleId:"trainer-interaction-gap", title:"Trainer interaction is overdue", reason:"No recorded trainer interaction in 21 days.", priority:"MEDIUM", action:"Schedule a meaningful trainer check-in", role:"TRAINER", dueDays:3 }] : []; }
