import { BarChart3, BellRing, ClipboardCheck, Settings, Users } from "lucide-react";
import type { Role } from "@/lib/permissions";

type Item = { href: string; label: string; icon: typeof BarChart3 };
const dashboard: Item = { href: "/", label: "My dashboard", icon: BarChart3 };
const memberDashboard: Item = { href: "/member", label: "My dashboard", icon: BarChart3 };
export const navigationByRole: Record<Role, Item[]> = {
  OWNER: [dashboard, { href: "/attention", label: "Attention", icon: BellRing }, { href: "/members", label: "Members", icon: Users }, { href: "/trainer", label: "Trainer actions", icon: ClipboardCheck }, { href: "/outcomes", label: "Outcomes", icon: ClipboardCheck }, { href: "/journeys", label: "Member journeys", icon: ClipboardCheck }, { href: "/experience", label: "Experience", icon: ClipboardCheck }, { href: "/floor", label: "Gym floor", icon: ClipboardCheck }, { href: "/reception", label: "Reception", icon: ClipboardCheck }, { href: "/community", label: "Community", icon: Users }, { href: "/notifications", label: "Notifications", icon: BellRing }, { href: "/reports", label: "Reports", icon: BarChart3 }, { href: "/staff", label: "Staff", icon: Users }, { href: "/training", label: "Training Center", icon: ClipboardCheck }, { href: "/settings", label: "Settings", icon: Settings }],
  MANAGER: [dashboard, { href: "/attention", label: "Attention", icon: BellRing }, { href: "/members", label: "Members", icon: Users }, { href: "/trainer", label: "Trainer actions", icon: ClipboardCheck }, { href: "/outcomes", label: "Outcomes", icon: ClipboardCheck }, { href: "/journeys", label: "Member journeys", icon: ClipboardCheck }, { href: "/experience", label: "Experience", icon: ClipboardCheck }, { href: "/floor", label: "Gym floor", icon: ClipboardCheck }, { href: "/reception", label: "Reception", icon: ClipboardCheck }, { href: "/community", label: "Community", icon: Users }, { href: "/notifications", label: "Notifications", icon: BellRing }, { href: "/training", label: "Training Center", icon: ClipboardCheck }],
  TRAINER: [dashboard, { href: "/trainer", label: "My actions", icon: ClipboardCheck }, { href: "/members", label: "My members", icon: Users }, { href: "/journeys", label: "Member journeys", icon: ClipboardCheck }, { href: "/floor", label: "Gym floor", icon: ClipboardCheck }, { href: "/community", label: "Community", icon: Users }, { href: "/notifications", label: "Notifications", icon: BellRing }, { href: "/training", label: "Training Center", icon: ClipboardCheck }],
  RECEPTION: [dashboard, { href: "/reception", label: "Reception", icon: ClipboardCheck }, { href: "/members", label: "Member lookup", icon: Users }, { href: "/floor", label: "Gym floor", icon: ClipboardCheck }, { href: "/notifications", label: "Notifications", icon: BellRing }, { href: "/training", label: "Training Center", icon: ClipboardCheck }],
  MEMBER: [memberDashboard, { href: "/community", label: "My community", icon: Users }, { href: "/training", label: "Training Center", icon: ClipboardCheck }],
};
