import { notFound } from "next/navigation";
import { DsBadge, DsCard } from "@/components/design-system";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { assertMemberAccess } from "@/lib/members";

const tone = (state: string) => state === "AT_RISK" ? "danger" : ["DECLINING", "PLATEAU"].includes(state) ? "warning" : "success" as const;
export default async function MemberIntelligencePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const user = await requireUser();
  try { await assertMemberAccess(user, id, false); } catch { notFound(); }
  const member = await db.member.findFirst({ where: { id, gymId: user.gymId }, include: { trainer: { select: { name: true } }, stateHistory: { orderBy: { calculatedAt: "desc" }, take: 8 }, attentionItems: { where: { status: { in: ["OPEN", "ASSIGNED", "IN_PROGRESS"] } }, orderBy: { dueAt: "asc" } } } });
  if (!member) notFound(); const current = member.stateHistory[0];
  return <><header className="page-header"><div><p className="eyebrow">Member intelligence</p><h1>{member.fullName}</h1><p>Current behavioral state, active recommendations, and state history.</p></div><DsBadge tone={tone(member.memberState)}>{member.memberState.replaceAll("_", " ")}</DsBadge></header><div className="profile-actions"><a className="button button-outline" href={`/members/${id}`}>Back to member</a></div><section className="detail-grid"><DsCard><h2 className="section-title">Current state</h2><p className="stat-value">{member.memberState.replaceAll("_", " ")}</p><p className="small">{current?.reason ?? "No state transition has been calculated yet."}</p><p className="small">Since {current?.calculatedAt.toLocaleDateString("en-IN") ?? member.createdAt.toLocaleDateString("en-IN")} · Trainer: {member.trainer?.name ?? "Unassigned"}</p></DsCard><DsCard><h2 className="section-title">Recommended next action</h2>{member.attentionItems[0] ? <><strong>{member.attentionItems[0].recommendedAction}</strong><p className="small">{member.attentionItems[0].reason}</p><p className="small">Due {member.attentionItems[0].dueAt.toLocaleDateString("en-IN")}</p></> : <p className="small">No active intervention is needed.</p>}</DsCard></section><section className="detail-grid"><DsCard><h2 className="section-title">Active attention</h2>{member.attentionItems.length ? member.attentionItems.map((item) => <div className="detail-row" key={item.id}><strong>{item.title}</strong><span>{item.reason}</span><span>{item.priority} · {item.assignedRole}</span></div>) : <p className="small">No open items.</p>}</DsCard><DsCard><h2 className="section-title">State history</h2>{member.stateHistory.length ? member.stateHistory.map((entry) => <div className="detail-row" key={entry.id}><strong>{entry.state.replaceAll("_", " ")}</strong><span>{entry.reason}</span><span>{entry.calculatedAt.toLocaleDateString("en-IN")}</span></div>) : <p className="small">State history will appear after the first transition.</p>}</DsCard></section></>;
}
