import { notFound } from "next/navigation";
import { DsBadge, DsCard } from "@/components/design-system";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { assertMemberAccess } from "@/lib/members";

type Params = Promise<{ id: string }>;
const label = (value: string) => value.replaceAll("_", " ");
export default async function MemberOutcomeHistory({ params }: { params: Params }) { const user = await requireUser(); const { id } = await params; try { await assertMemberAccess(user, id, false); } catch { notFound(); } const [member, outcomes] = await Promise.all([db.member.findFirst({ where: { id, gymId: user.gymId }, select: { fullName: true } }), db.outcome.findMany({ where: { gymId: user.gymId, memberId: id, ...(user.role === "TRAINER" ? { intervention: { assignedToId: user.id } } : {}) }, include: { intervention: true }, orderBy: { evaluationDate: "desc" } })]); if (!member) notFound(); return <><header className="page-header"><div><p className="eyebrow">Member history</p><h1>Outcomes for {member.fullName}</h1><p>What was tried, what changed, and what remains to do.</p></div><a className="button button-outline" href={`/members/${id}`}>Back to member</a></header><DsCard>{outcomes.length ? <div className="list">{outcomes.map((outcome) => <article className="trainer-work-item" key={outcome.id}><div><a className="member-link" href={`/outcomes/${outcome.interventionId}`}><strong>{outcome.intervention.title}</strong><span>{label(outcome.intervention.type)} · {outcome.evaluationDate.toLocaleDateString("en-IN")}</span></a><p className="small">Problem: {outcome.intervention.reason}</p><p className="small">Action: {outcome.intervention.actionTaken ?? "—"} · Next: {outcome.nextAction ?? "No next action recorded"}</p></div><DsBadge tone={outcome.outcomeStatus === "IMPROVED" ? "success" : outcome.outcomeStatus === "DECLINED" ? "danger" : "warning"}>{label(outcome.outcomeStatus)}</DsBadge></article>)}</div> : <p className="empty-state"><strong>No evaluated outcomes yet</strong><br/>Outcome evaluations will explain what has worked for this member.</p>}</DsCard></>; }
